Octavio: I pledge my honor that I have abided by the Stevens Honor System.

Once again, the same sources were used, in addition to the class notes.

1 Naive Bayes Classification [40 pts]
Use the following code to generate the train data set. The code will generate a random data set with four features and classes.

Importing Modules:

In [31]:
from sklearn import datasets
import numpy
from scipy.stats import norm
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

a. [5 pts] Compute the prior probability of each class, p(Ck).

In [32]:
X, y = datasets.make_blobs(n_samples=400, n_features=5, centers=4, cluster_std=2, random_state=100)
pri = numpy.bincount(y) / len(y)
print('Prior Probabilities: ', pri)

Prior Probabilities:  [0.25 0.25 0.25 0.25]


b. [10 pts] Compute the likelihood p(X|Ck).

In [33]:
clas1 = numpy.unique(y)
m = numpy.zeros((len(clas1), X.shape[1]))

for x, c in enumerate(clas1):
    m[x] = X[y == c].mean(axis=0)

clas2 = numpy.unique(y)
vari = numpy.zeros((len(clas2), X.shape[1]))

for x, c in enumerate(clas2):
    vari[x] = X[y == c].var(axis=0)

cList = numpy.zeros((X.shape[0], len(numpy.unique(y))))

for c in numpy.unique(y):
    cList[:, c] = norm(m[c], numpy.sqrt(vari[c])).pdf(X).prod(axis=1)

print('Likelihoods p(X|Ck): ', cList)

Likelihoods p(X|Ck):  [[4.35737431e-19 5.83470609e-36 1.65617426e-23 6.68636482e-05]
 [3.37890351e-18 3.74816408e-29 3.43372487e-07 1.15217600e-30]
 [1.51666045e-04 1.60401115e-28 6.93442926e-23 4.77305265e-19]
 ...
 [2.08939633e-19 9.37365394e-30 4.84965368e-20 1.96815445e-05]
 [3.42781461e-17 4.61639896e-28 1.82075584e-04 2.58663455e-21]
 [8.88281347e-16 1.19706820e-26 1.16782062e-15 5.94553837e-06]]


c. [15 pts] Compute the posterior probability of each point p(Ck|X). Assign the class ID to each point.

In [34]:
pp= cList*pri
ca= numpy.argmax(pp, axis=1)
print('Posterior Probabilities: ', pp)
print('')
print('Class Assignments: ', ca)

Posterior Probabilities:  [[1.08934358e-19 1.45867652e-36 4.14043566e-24 1.67159121e-05]
 [8.44725876e-19 9.37041019e-30 8.58431217e-08 2.88043999e-31]
 [3.79165112e-05 4.01002788e-29 1.73360732e-23 1.19326316e-19]
 ...
 [5.22349081e-20 2.34341348e-30 1.21241342e-20 4.92038613e-06]
 [8.56953653e-18 1.15409974e-28 4.55188961e-05 6.46658639e-22]
 [2.22070337e-16 2.99267050e-27 2.91955156e-16 1.48638459e-06]]

Class Assignments:  [3 2 0 3 3 1 3 1 2 2 0 2 2 3 0 3 2 3 1 2 2 1 1 3 1 3 1 0 2 0 2 3 0 0 3 0 1
 1 1 2 1 3 2 0 0 3 3 2 3 1 3 1 2 2 3 1 0 1 3 2 2 0 3 1 1 0 3 2 1 0 1 2 1 2
 0 0 1 1 2 0 0 1 1 0 1 0 0 3 2 1 1 3 3 0 2 1 3 2 3 1 2 2 1 1 1 1 2 3 2 3 1
 3 0 3 2 2 1 1 1 3 1 3 0 3 0 2 1 3 3 2 3 2 3 0 2 2 2 3 1 3 2 0 0 0 0 2 3 1
 3 0 0 1 3 1 2 0 0 3 0 3 1 0 0 2 0 3 1 2 2 3 0 0 3 1 1 0 3 0 0 0 1 0 1 0 1
 0 3 2 1 2 2 0 1 3 2 3 3 0 3 2 0 0 1 3 0 3 3 2 1 3 0 1 2 2 3 1 2 1 2 3 1 0
 1 3 1 0 0 1 0 0 3 0 1 0 3 1 3 3 0 0 1 3 0 0 2 1 2 2 0 3 0 0 1 3 3 2 0 0 1
 2 2 1 3 0 2 1 3 3 2 1 0 2 0 0 3 3 2 0 3 2 2

d. [5 pts] Construct the confusion matrix to show the classification rate.

In [35]:
print('Confusion Matrix: ', ca)

Confusion Matrix:  [3 2 0 3 3 1 3 1 2 2 0 2 2 3 0 3 2 3 1 2 2 1 1 3 1 3 1 0 2 0 2 3 0 0 3 0 1
 1 1 2 1 3 2 0 0 3 3 2 3 1 3 1 2 2 3 1 0 1 3 2 2 0 3 1 1 0 3 2 1 0 1 2 1 2
 0 0 1 1 2 0 0 1 1 0 1 0 0 3 2 1 1 3 3 0 2 1 3 2 3 1 2 2 1 1 1 1 2 3 2 3 1
 3 0 3 2 2 1 1 1 3 1 3 0 3 0 2 1 3 3 2 3 2 3 0 2 2 2 3 1 3 2 0 0 0 0 2 3 1
 3 0 0 1 3 1 2 0 0 3 0 3 1 0 0 2 0 3 1 2 2 3 0 0 3 1 1 0 3 0 0 0 1 0 1 0 1
 0 3 2 1 2 2 0 1 3 2 3 3 0 3 2 0 0 1 3 0 3 3 2 1 3 0 1 2 2 3 1 2 1 2 3 1 0
 1 3 1 0 0 1 0 0 3 0 1 0 3 1 3 3 0 0 1 3 0 0 2 1 2 2 0 3 0 0 1 3 3 2 0 0 1
 2 2 1 3 0 2 1 3 3 2 1 0 2 0 0 3 3 2 0 3 2 2 3 2 2 1 0 3 0 1 2 0 3 1 1 2 2
 0 0 2 3 1 0 2 0 0 1 0 1 1 3 2 0 1 3 3 1 3 2 2 3 2 1 1 1 1 2 2 3 2 0 0 2 2
 0 1 1 0 1 2 1 3 1 2 0 0 1 0 3 3 2 2 2 2 0 3 2 3 2 1 3 2 1 1 2 2 2 3 2 2 0
 2 0 2 0 1 2 0 3 1 3 2 1 3 3 3 3 0 3 1 0 1 0 0 2 3 1 1 3 2 3]


e. [5 pts] Classify the target using sklearn.native bayes.GaussianNB. Report the accuracy of the model.

In [36]:
model = GaussianNB()
model.fit(X, y)
predicted = model.predict(X)

acc = accuracy_score(y, predicted)
print("Model Accuracy:", "{:.2f}".format(acc))


Model Accuracy: 1.00
